"""SQLAlchemy declarative base and shared column types.

Conventions enforced here so no model has to remember them (CLAUDE.md §6):
  * primary keys are UUIDv7, generated server-side (ADR-0009)
  * timestamps are TIMESTAMPTZ, stored UTC
  * mutable tables get created_at/updated_at; append-only tables get created_at only
"""

from __future__ import annotations

import datetime as dt
import uuid
from typing import Annotated, Any

from sqlalchemy import BigInteger, DateTime, MetaData, Numeric, String, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Predictable constraint names make Alembic autogenerate stable across machines.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# --------------------------------------------------------------------------- column types

#: UUIDv7 primary key, generated by Postgres so ids are time-ordered even under concurrency.
UuidPk = Annotated[
    uuid.UUID,
    mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("uuid_generate_v7()"),
    ),
]

UuidFk = Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True))]

#: Money. Integer paise, never float (ADR-0009).
Paise = Annotated[int, mapped_column(BigInteger)]

#: Area in square metres.
Sqm = Annotated[float, mapped_column(Numeric(14, 2))]

#: Mass in kilograms.
Kg = Annotated[float, mapped_column(Numeric(14, 3))]

#: Confidence in [0, 1].
Confidence = Annotated[float, mapped_column(Numeric(4, 3))]

Timestamp = Annotated[dt.datetime, mapped_column(DateTime(timezone=True))]

ShortText = Annotated[str, mapped_column(String(255))]

Json = Annotated[dict[str, Any], mapped_column(JSONB)]

#: A JSONB array column. Used where the payload is a list of records
#: (evidence refs, discrepancy claims, rule results).
JsonList = Annotated[list[Any], mapped_column(JSONB)]


# --------------------------------------------------------------------------- mixins


class TimestampMixin:
    """For mutable entities."""

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class AppendOnlyMixin:
    """For tables that are never updated (DR-04).

    Correction is a new row plus supersession — never an UPDATE or DELETE. There is
    deliberately no ``updated_at``: its absence is the signal to a reader that this table
    does not change. Revocation of UPDATE/DELETE at the grant level is applied in the
    migration, so the rule is enforced by the database rather than by convention.
    """

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
