"""conversation turns for the assistant

Revision ID: a63640eada8d
Revises: ff37df671223
Create Date: 2026-08-23 20:45:53.193706
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'a63640eada8d'
down_revision: str | None = 'ff37df671223'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turn',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('shape', sa.String(length=16), nullable=False),
    sa.Column('lookup_key', sa.String(length=48), nullable=True),
    sa.Column('intent_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fell_back', sa.Boolean(), nullable=False),
    sa.Column('packet_id', sa.UUID(), nullable=True),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_conversation_turn_actor_user_id_app_user')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_conversation_turn_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_conversation_turn_organization_id_organization')),
    sa.ForeignKeyConstraint(['packet_id'], ['decision_packet.id'], name=op.f('fk_conversation_turn_packet_id_decision_packet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turn'))
    )
    op.create_index('ix_conversation_turn_conversation', 'conversation_turn', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_conversation_turn_org', 'conversation_turn', ['organization_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


    # DR-04: a new append-only table needs its guard, or the invariant covers every
    # table except the newest one — which is exactly where it would first be broken.
    op.execute(
        """
        CREATE TRIGGER conversation_turn_append_only
        BEFORE UPDATE OR DELETE ON conversation_turn
        FOR EACH ROW EXECUTE FUNCTION agrivardhak_append_only_guard();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS conversation_turn_append_only ON conversation_turn;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_turn_org', table_name='conversation_turn')
    op.drop_index('ix_conversation_turn_conversation', table_name='conversation_turn')
    op.drop_table('conversation_turn')
    # ### end Alembic commands ###
