"""initial schema

Revision ID: b8effdc6a2cb
Revises: 
Create Date: 2026-08-22 22:29:03.346925
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'b8effdc6a2cb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_policy',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('attribute', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('half_life_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('stale_after_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tolerance_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_policy')),
    sa.UniqueConstraint('attribute', name=op.f('uq_attribute_policy_attribute'))
    )
    op.create_table('crop',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_hi', sa.String(length=255), nullable=True),
    sa.Column('default_season', sa.Enum('KHARIF', 'RABI', 'ZAID', 'PERENNIAL', name='season'), nullable=False),
    sa.Column('is_perennial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop')),
    sa.UniqueConstraint('name', name=op.f('uq_crop_name'))
    )
    op.create_table('data_source',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('FIELD_OFFICER', 'FARMER_SELF_REPORT', 'AI_INFERENCE', 'EXTERNAL_SOURCE', 'ORG_RECORD', 'FIXTURE', name='source_type'), nullable=False),
    sa.Column('base_trust', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('cadence', sa.String(length=64), nullable=True),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source')),
    sa.UniqueConstraint('key', name=op.f('uq_data_source_key'))
    )
    op.create_table('evidence_snapshot',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_snapshot')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_evidence_snapshot_content_hash'))
    )
    op.create_table('farmer',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('village', sa.String(length=160), nullable=True),
    sa.Column('block', sa.String(length=160), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('tract', sa.String(length=40), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('is_woman_farmer', sa.Boolean(), nullable=True),
    sa.Column('has_disability', sa.Boolean(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer'))
    )
    op.create_table('organization',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('type', sa.Enum('FPO', 'PACS', 'SHG', 'FPC', 'COOPERATIVE', name='organization_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_form', sa.String(length=120), nullable=True),
    sa.Column('registration_no', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_table('prediction',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('module_version', sa.String(length=32), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=120), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_end', sa.Date(), nullable=True),
    sa.Column('inputs_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction'))
    )
    op.create_index('ix_prediction_module', 'prediction', ['module', 'module_version'], unique=False)
    op.create_index('ix_prediction_subject', 'prediction', ['subject_type', 'subject_id', 'metric'], unique=False)
    op.create_table('scheme',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_hi', sa.String(length=255), nullable=True),
    sa.Column('authority', sa.String(length=160), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_text', sa.Text(), nullable=True),
    sa.Column('eligibility_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_documents', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('benefit_paise', sa.BigInteger(), nullable=True),
    sa.Column('benefit_description', sa.Text(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme')),
    sa.UniqueConstraint('code', name=op.f('uq_scheme_code'))
    )
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_app_user_farmer_id_farmer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_app_user_phone'))
    )
    op.create_table('buyer',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('WHOLESALER', 'PROCESSOR', 'RETAILER', 'EXPORTER', 'INSTITUTIONAL', 'GOVERNMENT', 'ECOMMERCE', 'AGGREGATOR', name='buyer_type'), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('reliability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('rejection_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('min_quantity_kg', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('max_quantity_kg', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('quality_requirement', sa.Enum('A', 'B', 'C', 'REJECT', name='grade'), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_buyer_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer'))
    )
    op.create_index('ix_buyer_org', 'buyer', ['organization_id'], unique=False)
    op.create_table('eligibility_assessment',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ELIGIBLE', 'LIKELY_ELIGIBLE', 'INSUFFICIENT_DATA', 'NOT_ELIGIBLE', name='eligibility_status'), nullable=False),
    sa.Column('rule_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_attributes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('missing_documents', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('estimated_benefit_paise', sa.BigInteger(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_eligibility_assessment_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_eligibility_assessment_organization_id_organization')),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], name=op.f('fk_eligibility_assessment_scheme_id_scheme')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligibility_assessment'))
    )
    op.create_index('ix_eligibility_farmer_scheme', 'eligibility_assessment', ['farmer_id', 'scheme_id', 'assessed_at'], unique=False)
    op.create_index('ix_eligibility_scheme_status', 'eligibility_assessment', ['scheme_id', 'status'], unique=False)
    op.create_table('external_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('kind', sa.Enum('WEATHER', 'MARKET_PRICE', 'SCHEME', 'NEWS', 'DEMAND', 'FUEL_PRICE', name='external_record_kind'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_external_record_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_record')),
    sa.UniqueConstraint('kind', 'dedupe_key', name='kind_dedupe')
    )
    op.create_index('ix_external_record_kind_fetched', 'external_record', ['kind', 'fetched_at'], unique=False)
    op.create_table('farm',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('operator_farmer_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('village', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_farmer_id'], ['farmer.id'], name=op.f('fk_farm_operator_farmer_id_farmer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm'))
    )
    op.create_table('governance_profile',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=True),
    sa.Column('approval_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_governance_profile_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_governance_profile')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_governance_profile_organization_id'))
    )
    op.create_table('lot',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'REJECT', name='grade'), nullable=True),
    sa.Column('ready_date', sa.Date(), nullable=True),
    sa.Column('origin_location', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_lot_crop_id_crop')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_lot_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot'))
    )
    op.create_index('ix_lot_org_crop', 'lot', ['organization_id', 'crop_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'DIRECTOR', 'STAFF', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXITED', name='membership_status'), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.Column('shares_held', sa.Integer(), nullable=True),
    sa.Column('patronage_units', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_membership_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_membership_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership')),
    sa.UniqueConstraint('farmer_id', 'organization_id', name='farmer_org')
    )
    op.create_index('ix_membership_org_status', 'membership', ['organization_id', 'status'], unique=False)
    op.create_table('org_resource',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('WORKING_CAPITAL', 'WAREHOUSE', 'COLD_STORAGE', 'MACHINERY', 'VEHICLE', 'PROCESSING_UNIT', 'INPUT_INVENTORY', name='org_resource_type'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('value_paise', sa.BigInteger(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_org_resource_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_resource'))
    )
    op.create_table('risk_register_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Enum('CLIMATE', 'WEATHER', 'CROP_HEALTH', 'MARKET', 'POLICY', 'SUPPLY_CHAIN', 'GLOBAL', name='risk_domain'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='likelihood'), nullable=False),
    sa.Column('impact', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='impact'), nullable=False),
    sa.Column('farmers_affected', sa.Integer(), nullable=True),
    sa.Column('area_affected_sqm', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('value_at_risk_paise', sa.BigInteger(), nullable=True),
    sa.Column('causal_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_role', sa.Enum('PLATFORM_ADMIN', 'FPO_CEO', 'FARMER', 'FIELD_OFFICER', 'MARKET_OFFICER', 'FINANCE_OFFICER', 'RESEARCHER', name='role'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'MITIGATING', 'CLOSED', name='risk_status'), nullable=False),
    sa.Column('review_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_risk_register_entry_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_register_entry'))
    )
    op.create_index('ix_risk_org_status', 'risk_register_entry', ['organization_id', 'status'], unique=False)
    op.create_table('scheme_application',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('cycle_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'ELIGIBLE', 'DOCUMENTS_PENDING', 'APPLIED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='application_status'), nullable=False),
    sa.Column('documents_on_record', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('applied_on', sa.Date(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('benefit_received_paise', sa.BigInteger(), nullable=True),
    sa.Column('reference_no', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_scheme_application_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_scheme_application_organization_id_organization')),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], name=op.f('fk_scheme_application_scheme_id_scheme')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme_application')),
    sa.UniqueConstraint('farmer_id', 'scheme_id', 'cycle_year', name='farmer_scheme_year')
    )
    op.create_index('ix_scheme_application_status', 'scheme_application', ['organization_id', 'status'], unique=False)
    op.create_table('variety',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('base_yield_kg_per_ha', sa.Float(), nullable=True),
    sa.Column('grade_potential', sa.Enum('A', 'B', 'C', 'REJECT', name='grade'), nullable=True),
    sa.Column('water_requirement_mm', sa.Float(), nullable=True),
    sa.Column('agro_zone', sa.String(length=120), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_variety_crop_id_crop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variety'))
    )
    op.create_index('ix_variety_crop', 'variety', ['crop_id'], unique=False)
    op.create_table('announcement',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('OWNER', 'ORG_INTERNAL', 'SHARED_WITH_MEMBERS', 'PUBLIC', name='visibility_scope'), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_announcement_organization_id_organization')),
    sa.ForeignKeyConstraint(['published_by'], ['app_user.id'], name=op.f('fk_announcement_published_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement'))
    )
    op.create_table('audit_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.Enum('HUMAN', 'SYSTEM', 'AI', name='actor_kind'), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('authority', sa.String(length=64), nullable=True),
    sa.Column('evidence_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_record_actor_id_app_user')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_audit_record_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_record'))
    )
    op.create_index('ix_audit_actor', 'audit_record', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_subject', 'audit_record', ['subject_type', 'subject_id', 'created_at'], unique=False)
    op.create_table('buyer_match',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('headline_price_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('effective_price_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('attractiveness', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('negotiation_brief', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], name=op.f('fk_buyer_match_buyer_id_buyer')),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], name=op.f('fk_buyer_match_lot_id_lot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_match'))
    )
    op.create_index('ix_buyer_match_lot', 'buyer_match', ['lot_id'], unique=False)
    op.create_table('consent',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('SERVICE_DELIVERY', 'ORG_ANALYTICS', 'MODEL_IMPROVEMENT', 'ANONYMIZED_RESEARCH', name='consent_purpose'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('consent_text_version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['app_user.id'], name=op.f('fk_consent_captured_by_app_user')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_consent_farmer_id_farmer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent'))
    )
    op.create_index('ix_consent_farmer_purpose', 'consent', ['farmer_id', 'purpose', 'granted_at'], unique=False)
    op.create_table('decision_packet',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('asked_by', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asked_by'], ['app_user.id'], name=op.f('fk_decision_packet_asked_by_app_user')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_decision_packet_organization_id_organization')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshot.id'], name=op.f('fk_decision_packet_snapshot_id_evidence_snapshot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_packet'))
    )
    op.create_table('demand_signal',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=True),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'REJECT', name='grade'), nullable=True),
    sa.Column('price_paise_per_kg', sa.BigInteger(), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], name=op.f('fk_demand_signal_buyer_id_buyer')),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_demand_signal_crop_id_crop')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_demand_signal_organization_id_organization')),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_demand_signal_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_signal'))
    )
    op.create_index('ix_demand_signal_crop_window', 'demand_signal', ['crop_id', 'window_start'], unique=False)
    op.create_table('domain_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.Enum('HUMAN', 'SYSTEM', 'AI', name='actor_kind'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_domain_event_actor_id_app_user')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_domain_event_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_event'))
    )
    op.create_index('ix_domain_event_aggregate', 'domain_event', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_domain_event_type', 'domain_event', ['event_type', 'occurred_at'], unique=False)
    op.create_index('ix_domain_event_unpublished', 'domain_event', ['published_at'], unique=False)
    op.create_table('news_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('external_record_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.Enum('POLICY', 'CLIMATE', 'MARKET', 'SUPPLY_CHAIN', 'GLOBAL', 'INPUT_PRICE', name='news_domain'), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_record_id'], ['external_record.id'], name=op.f('fk_news_event_external_record_id_external_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_event'))
    )
    op.create_index('ix_news_event_domain_occurred', 'news_event', ['domain', 'occurred_at'], unique=False)
    op.create_table('observation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('attribute', sa.String(length=120), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.Enum('FIELD_OFFICER', 'FARMER_SELF_REPORT', 'AI_INFERENCE', 'EXTERNAL_SOURCE', 'ORG_RECORD', 'FIXTURE', name='source_type'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'DISPUTED', 'SUPERSEDED', name='verification_status'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_observation_confidence_range')),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_observation_source_id_data_source')),
    sa.ForeignKeyConstraint(['superseded_by'], ['observation.id'], name=op.f('fk_observation_superseded_by_observation')),
    sa.ForeignKeyConstraint(['verified_by'], ['app_user.id'], name=op.f('fk_observation_verified_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation'))
    )
    op.create_index('ix_observation_attribute', 'observation', ['attribute'], unique=False)
    op.create_index('ix_observation_subject', 'observation', ['subject_type', 'subject_id', 'attribute', 'observed_at'], unique=False)
    op.create_table('plot',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('registration_no', sa.String(length=120), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('soil_type', sa.String(length=80), nullable=True),
    sa.Column('irrigation_source', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_plot_farm_id_farm')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot'))
    )
    op.create_index('ix_plot_farm', 'plot', ['farm_id'], unique=False)
    op.create_table('role_grant',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'FPO_CEO', 'FARMER', 'FIELD_OFFICER', 'MARKET_OFFICER', 'FINANCE_OFFICER', 'RESEARCHER', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_role_grant_organization_id_organization')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_role_grant_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_grant')),
    sa.UniqueConstraint('user_id', 'organization_id', 'role', name='user_org_role')
    )
    op.create_table('crop_cycle',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('variety_id', sa.UUID(), nullable=False),
    sa.Column('season', sa.Enum('KHARIF', 'RABI', 'ZAID', 'PERENNIAL', name='season'), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'SOWN', 'GROWING', 'HARVEST_READY', 'HARVESTED', 'SOLD', 'CLOSED', 'ABANDONED', name='crop_cycle_status'), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('farming_method', sa.String(length=80), nullable=True),
    sa.Column('intercrop_group_id', sa.Uuid(), nullable=True),
    sa.Column('expected_yield_kg', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('actual_yield_kg', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('expected_grade', sa.Enum('A', 'B', 'C', 'REJECT', name='grade'), nullable=True),
    sa.Column('actual_grade', sa.Enum('A', 'B', 'C', 'REJECT', name='grade'), nullable=True),
    sa.Column('abandoned_reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area_sqm > 0', name=op.f('ck_crop_cycle_area_positive')),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], name=op.f('fk_crop_cycle_plot_id_plot')),
    sa.ForeignKeyConstraint(['variety_id'], ['variety.id'], name=op.f('fk_crop_cycle_variety_id_variety')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_cycle'))
    )
    op.create_index('ix_crop_cycle_plot_season', 'crop_cycle', ['plot_id', 'season', 'season_year'], unique=False)
    op.create_index('ix_crop_cycle_status', 'crop_cycle', ['status'], unique=False)
    op.create_table('data_discrepancy',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('attribute', sa.String(length=120), nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spread_pct', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tolerance_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('effective_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('effective_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'ACCEPTED', name='discrepancy_status'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_observation_id', sa.UUID(), nullable=True),
    sa.Column('resolution_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolution_observation_id'], ['observation.id'], name=op.f('fk_data_discrepancy_resolution_observation_id_observation')),
    sa.ForeignKeyConstraint(['resolved_by'], ['app_user.id'], name=op.f('fk_data_discrepancy_resolved_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_discrepancy'))
    )
    op.create_index('ix_discrepancy_status', 'data_discrepancy', ['status'], unique=False)
    op.create_index('ix_discrepancy_subject', 'data_discrepancy', ['subject_type', 'subject_id', 'attribute'], unique=False)
    op.create_table('farm_resource',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('CROP', 'LIVESTOCK', 'POULTRY', 'FISHERY', 'COMPOST', 'MANURE', 'AGROFORESTRY', 'WATER', 'EQUIPMENT', 'STRUCTURE', name='farm_resource_type'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_farm_resource_farm_id_farm')),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], name=op.f('fk_farm_resource_plot_id_plot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_resource'))
    )
    op.create_table('llm_call_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('packet_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('stop_reason', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['decision_packet.id'], name=op.f('fk_llm_call_log_packet_id_decision_packet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call_log'))
    )
    op.create_table('plot_tenure',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('holder_farmer_id', sa.UUID(), nullable=False),
    sa.Column('tenure_type', sa.Enum('OWNED', 'LEASED', 'SHARECROPPED', 'JOINT', 'ALLOTTED', 'OTHER', name='tenure_type'), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('evidence_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holder_farmer_id'], ['farmer.id'], name=op.f('fk_plot_tenure_holder_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], name=op.f('fk_plot_tenure_plot_id_plot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot_tenure'))
    )
    op.create_index('ix_plot_tenure_plot_valid', 'plot_tenure', ['plot_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('recommendation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('packet_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BUYER_SELECTION', 'LOT_ALLOCATION', 'CROP_PLAN', 'CROP_PROTECTION', 'FUNDING_ALLOCATION', 'PROCUREMENT', 'SCHEME_PURSUIT', 'RISK_MITIGATION', 'SCHEDULE', name='recommendation_type'), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('expected_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_value', sa.BigInteger(), nullable=True),
    sa.Column('value_unit', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('SUGGESTED', 'REVIEWED', 'APPROVED', 'EXECUTED', 'OUTCOME_RECORDED', 'REJECTED', 'SUPERSEDED', name='recommendation_status'), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('generator', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_recommendation_organization_id_organization')),
    sa.ForeignKeyConstraint(['packet_id'], ['decision_packet.id'], name=op.f('fk_recommendation_packet_id_decision_packet')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshot.id'], name=op.f('fk_recommendation_snapshot_id_evidence_snapshot')),
    sa.ForeignKeyConstraint(['superseded_by'], ['recommendation.id'], name=op.f('fk_recommendation_superseded_by_recommendation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation'))
    )
    op.create_index('ix_recommendation_org_status', 'recommendation', ['organization_id', 'status'], unique=False)
    op.create_index('ix_recommendation_target', 'recommendation', ['target_type', 'target_id'], unique=False)
    op.create_table('sale',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('buyer_match_id', sa.UUID(), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('agreed_on', sa.Date(), nullable=True),
    sa.Column('delivered_on', sa.Date(), nullable=True),
    sa.Column('payment_received_on', sa.Date(), nullable=True),
    sa.Column('actual_grade', sa.Enum('A', 'B', 'C', 'REJECT', name='grade'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], name=op.f('fk_sale_buyer_id_buyer')),
    sa.ForeignKeyConstraint(['buyer_match_id'], ['buyer_match.id'], name=op.f('fk_sale_buyer_match_id_buyer_match')),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], name=op.f('fk_sale_lot_id_lot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale'))
    )
    op.create_table('approval',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('role_exercised', sa.Enum('PLATFORM_ADMIN', 'FPO_CEO', 'FARMER', 'FIELD_OFFICER', 'MARKET_OFFICER', 'FINANCE_OFFICER', 'RESEARCHER', name='role'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'APPROVED_WITH_MODIFICATION', 'REJECTED', name='approval_decision'), nullable=False),
    sa.Column('approved_value', sa.BigInteger(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['app_user.id'], name=op.f('fk_approval_approver_user_id_app_user')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], name=op.f('fk_approval_recommendation_id_recommendation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    op.create_index('ix_approval_recommendation', 'approval', ['recommendation_id'], unique=False)
    op.create_table('calendar_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_hi', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin', sa.Enum('MANUAL', 'AUTO_GENERATED', 'AI_RECOMMENDED', 'OFFICIAL_DEADLINE', name='calendar_origin'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'COMPLETED', 'CANCELLED', name='calendar_status'), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visibility', sa.Enum('OWNER', 'ORG_INTERNAL', 'SHARED_WITH_MEMBERS', 'PUBLIC', name='visibility_scope'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['app_user.id'], name=op.f('fk_calendar_event_approved_by_app_user')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_calendar_event_created_by_app_user')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_calendar_event_organization_id_organization')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], name=op.f('fk_calendar_event_recommendation_id_recommendation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_event'))
    )
    op.create_index('ix_calendar_org_status', 'calendar_event', ['organization_id', 'status'], unique=False)
    op.create_index('ix_calendar_subject', 'calendar_event', ['subject_type', 'subject_id', 'starts_at'], unique=False)
    op.create_table('funding_allocation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('inputs_in_kind_paise', sa.BigInteger(), nullable=False),
    sa.Column('working_capital_paise', sa.BigInteger(), nullable=False),
    sa.Column('approved_on', sa.Date(), nullable=True),
    sa.Column('acknowledged_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycle.id'], name=op.f('fk_funding_allocation_crop_cycle_id_crop_cycle')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_funding_allocation_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_funding_allocation_organization_id_organization')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], name=op.f('fk_funding_allocation_recommendation_id_recommendation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_allocation'))
    )
    op.create_table('funding_requirement',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('input_plan_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('expected_scheme_benefit_paise', sa.BigInteger(), nullable=False),
    sa.Column('farmer_contribution_paise', sa.BigInteger(), nullable=False),
    sa.Column('recommended_support_paise', sa.BigInteger(), nullable=False),
    sa.Column('expected_revenue_paise', sa.BigInteger(), nullable=True),
    sa.Column('expected_farmer_roi', sa.Float(), nullable=True),
    sa.Column('computation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_sufficiency', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycle.id'], name=op.f('fk_funding_requirement_crop_cycle_id_crop_cycle')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_funding_requirement_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_funding_requirement_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_requirement'))
    )
    op.create_index('ix_funding_requirement_cycle', 'funding_requirement', ['crop_cycle_id'], unique=False)
    op.create_table('input_application',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('SEED', 'NUTRIENT', 'CROP_PROTECTION', 'WATER', 'LABOUR', 'ENERGY', name='input_category'), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('cost_paise', sa.BigInteger(), nullable=True),
    sa.Column('applied_on', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycle.id'], name=op.f('fk_input_application_crop_cycle_id_crop_cycle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_input_application'))
    )
    op.create_index('ix_input_application_cycle', 'input_application', ['crop_cycle_id'], unique=False)
    op.create_table('intervention',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=True),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('cost_paise', sa.BigInteger(), nullable=True),
    sa.Column('followed', sa.Enum('YES', 'PARTIAL', 'NO', 'UNKNOWN', name='adherence'), nullable=False),
    sa.Column('fidelity', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.Column('deviation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fidelity IS NULL OR (fidelity >= 0 AND fidelity <= 1)', name=op.f('ck_intervention_fidelity_range')),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycle.id'], name=op.f('fk_intervention_crop_cycle_id_crop_cycle')),
    sa.ForeignKeyConstraint(['executed_by'], ['app_user.id'], name=op.f('fk_intervention_executed_by_app_user')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_intervention_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], name=op.f('fk_intervention_recommendation_id_recommendation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intervention'))
    )
    op.create_index('ix_intervention_cycle', 'intervention', ['crop_cycle_id'], unique=False)
    op.create_index('ix_intervention_recommendation', 'intervention', ['recommendation_id'], unique=False)
    op.create_table('lot_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'REJECT', name='grade'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycle.id'], name=op.f('fk_lot_item_crop_cycle_id_crop_cycle')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('fk_lot_item_farmer_id_farmer')),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], name=op.f('fk_lot_item_lot_id_lot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot_item'))
    )
    op.create_table('resource_flow',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('from_resource_id', sa.UUID(), nullable=False),
    sa.Column('to_resource_id', sa.UUID(), nullable=False),
    sa.Column('flow_type', sa.Enum('FEED', 'FERTILITY', 'WATER', 'ENERGY', 'RESIDUE', 'LABOUR', 'INCOME', name='resource_flow_type'), nullable=False),
    sa.Column('quantity_per_cycle', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_resource_id'], ['farm_resource.id'], name=op.f('fk_resource_flow_from_resource_id_farm_resource')),
    sa.ForeignKeyConstraint(['to_resource_id'], ['farm_resource.id'], name=op.f('fk_resource_flow_to_resource_id_farm_resource')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_flow'))
    )
    op.create_table('outcome',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=True),
    sa.Column('metric', sa.String(length=120), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('observed_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('external_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], name=op.f('fk_outcome_intervention_id_intervention')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcome'))
    )
    op.create_index('ix_outcome_target', 'outcome', ['target_type', 'target_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('calendar_event_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_role', sa.Enum('PLATFORM_ADMIN', 'FPO_CEO', 'FARMER', 'FIELD_OFFICER', 'MARKET_OFFICER', 'FINANCE_OFFICER', 'RESEARCHER', name='role'), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['app_user.id'], name=op.f('fk_task_assignee_user_id_app_user')),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_event.id'], name=op.f('fk_task_calendar_event_id_calendar_event')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_task_organization_id_organization')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], name=op.f('fk_task_recommendation_id_recommendation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_index('ix_task_org_status', 'task', ['organization_id', 'status'], unique=False)
    op.create_table('attribution',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('outcome_id', sa.UUID(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('strength', sa.Enum('HIGH', 'MODERATE', 'UNCERTAIN', 'CONFOUNDED', name='attribution_strength'), nullable=False),
    sa.Column('confounders', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], name=op.f('fk_attribution_intervention_id_intervention')),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], name=op.f('fk_attribution_outcome_id_outcome')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribution'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribution')
    op.drop_index('ix_task_org_status', table_name='task')
    op.drop_table('task')
    op.drop_index('ix_outcome_target', table_name='outcome')
    op.drop_table('outcome')
    op.drop_table('resource_flow')
    op.drop_table('lot_item')
    op.drop_index('ix_intervention_recommendation', table_name='intervention')
    op.drop_index('ix_intervention_cycle', table_name='intervention')
    op.drop_table('intervention')
    op.drop_index('ix_input_application_cycle', table_name='input_application')
    op.drop_table('input_application')
    op.drop_index('ix_funding_requirement_cycle', table_name='funding_requirement')
    op.drop_table('funding_requirement')
    op.drop_table('funding_allocation')
    op.drop_index('ix_calendar_subject', table_name='calendar_event')
    op.drop_index('ix_calendar_org_status', table_name='calendar_event')
    op.drop_table('calendar_event')
    op.drop_index('ix_approval_recommendation', table_name='approval')
    op.drop_table('approval')
    op.drop_table('sale')
    op.drop_index('ix_recommendation_target', table_name='recommendation')
    op.drop_index('ix_recommendation_org_status', table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index('ix_plot_tenure_plot_valid', table_name='plot_tenure')
    op.drop_table('plot_tenure')
    op.drop_table('llm_call_log')
    op.drop_table('farm_resource')
    op.drop_index('ix_discrepancy_subject', table_name='data_discrepancy')
    op.drop_index('ix_discrepancy_status', table_name='data_discrepancy')
    op.drop_table('data_discrepancy')
    op.drop_index('ix_crop_cycle_status', table_name='crop_cycle')
    op.drop_index('ix_crop_cycle_plot_season', table_name='crop_cycle')
    op.drop_table('crop_cycle')
    op.drop_table('role_grant')
    op.drop_index('ix_plot_farm', table_name='plot')
    op.drop_table('plot')
    op.drop_index('ix_observation_subject', table_name='observation')
    op.drop_index('ix_observation_attribute', table_name='observation')
    op.drop_table('observation')
    op.drop_index('ix_news_event_domain_occurred', table_name='news_event')
    op.drop_table('news_event')
    op.drop_index('ix_domain_event_unpublished', table_name='domain_event')
    op.drop_index('ix_domain_event_type', table_name='domain_event')
    op.drop_index('ix_domain_event_aggregate', table_name='domain_event')
    op.drop_table('domain_event')
    op.drop_index('ix_demand_signal_crop_window', table_name='demand_signal')
    op.drop_table('demand_signal')
    op.drop_table('decision_packet')
    op.drop_index('ix_consent_farmer_purpose', table_name='consent')
    op.drop_table('consent')
    op.drop_index('ix_buyer_match_lot', table_name='buyer_match')
    op.drop_table('buyer_match')
    op.drop_index('ix_audit_subject', table_name='audit_record')
    op.drop_index('ix_audit_actor', table_name='audit_record')
    op.drop_table('audit_record')
    op.drop_table('announcement')
    op.drop_index('ix_variety_crop', table_name='variety')
    op.drop_table('variety')
    op.drop_index('ix_scheme_application_status', table_name='scheme_application')
    op.drop_table('scheme_application')
    op.drop_index('ix_risk_org_status', table_name='risk_register_entry')
    op.drop_table('risk_register_entry')
    op.drop_table('org_resource')
    op.drop_index('ix_membership_org_status', table_name='membership')
    op.drop_table('membership')
    op.drop_index('ix_lot_org_crop', table_name='lot')
    op.drop_table('lot')
    op.drop_table('governance_profile')
    op.drop_table('farm')
    op.drop_index('ix_external_record_kind_fetched', table_name='external_record')
    op.drop_table('external_record')
    op.drop_index('ix_eligibility_scheme_status', table_name='eligibility_assessment')
    op.drop_index('ix_eligibility_farmer_scheme', table_name='eligibility_assessment')
    op.drop_table('eligibility_assessment')
    op.drop_index('ix_buyer_org', table_name='buyer')
    op.drop_table('buyer')
    op.drop_table('app_user')
    op.drop_table('scheme')
    op.drop_index('ix_prediction_subject', table_name='prediction')
    op.drop_index('ix_prediction_module', table_name='prediction')
    op.drop_table('prediction')
    op.drop_table('organization')
    op.drop_table('farmer')
    op.drop_table('evidence_snapshot')
    op.drop_table('data_source')
    op.drop_table('crop')
    op.drop_table('attribute_policy')
    # ### end Alembic commands ###
