"""external record kinds for the six fetched batches

ADR-0013. The batch fetchers in ``seed/`` cache MSP, cost-of-cultivation, variety,
production and procurement payloads that had nowhere to land: ``ExternalRecordKind`` stopped
at the five kinds the weather and mandi adapters needed.

Hand-written rather than autogenerated. Alembic's autogenerate does not diff enum *values* —
it created ``external_record_kind`` inline in the initial schema and will not notice new
members, so a missing migration here shows up as a runtime ``InvalidTextRepresentation``
rather than as a pending revision.

``ALTER TYPE ... ADD VALUE`` runs outside the migration's transaction. Postgres 16 permits it
inside one, but a value added in a transaction cannot be *used* until that transaction
commits, and the loader that follows would fail in exactly the confusing way this comment
exists to prevent.

Revision ID: c1000000extkinds
Revises: a63640eada8d
"""

from collections.abc import Sequence

from alembic import op

revision: str = "c1000000extkinds"
down_revision: str | None = "a63640eada8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NEW_KINDS = ("MSP", "COST_OF_CULTIVATION", "VARIETY", "PRODUCTION", "PROCUREMENT")


def upgrade() -> None:
    with op.get_context().autocommit_block():
        for kind in NEW_KINDS:
            op.execute(f"ALTER TYPE external_record_kind ADD VALUE IF NOT EXISTS '{kind}'")


def downgrade() -> None:
    """Not reversible.

    Postgres has no ``ALTER TYPE ... DROP VALUE``. Removing a member means recreating the
    type and rewriting every column that uses it, which would destroy rows that legitimately
    carry the new kinds. Leaving the values in place is harmless — an unused enum member
    costs nothing — so this is a deliberate no-op rather than an oversight.
    """
