"""translation_memory: the bilingual corpus behind the page translator

ADR-0023. Written by hand rather than autogenerated: one table, and the check constraints
are the part worth reading.

Revision ID: c4000000transmem
Revises: c3000000chunkguard
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c4000000transmem"
down_revision: str | None = "c3000000chunkguard"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "translation_memory",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v7()"), nullable=False),
        sa.Column("source_lang", sa.String(length=8), nullable=False),
        sa.Column("target_lang", sa.String(length=8), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("origin in ('HUMAN', 'MACHINE')", name="ck_translation_memory_origin"),
        sa.CheckConstraint("source_lang <> target_lang", name="ck_translation_memory_direction"),
        sa.PrimaryKeyConstraint("id", name="pk_translation_memory"),
        sa.UniqueConstraint(
            "source_lang",
            "target_lang",
            "source_hash",
            name="uq_translation_memory_source_lang",
        ),
    )


def downgrade() -> None:
    op.drop_table("translation_memory")
