"""user password and demo account flag

Adds password sign-in to app_user.

``is_demo_account`` carries a ``server_default`` that the autogenerated version did not:
adding a NOT NULL column without one fails outright on a table that already has rows, and
this migration lands on databases that were seeded before login existed.

Revision ID: cc9339aa209e
Revises: b9000000guard
Create Date: 2026-08-23 11:14:33.895648
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'cc9339aa209e'
down_revision: str | None = 'b9000000guard'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column(
        'app_user',
        sa.Column(
            'is_demo_account',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'is_demo_account')
    op.drop_column('app_user', 'password_hash')
    # ### end Alembic commands ###
