"""domain_event ordering sequence

Gives the outbox a monotonic ordering column.

``dispatch_pending`` used to drain by ``id`` on the reasoning that UUIDv7 is time-ordered.
It is — to the millisecond. ``uuid_generate_v7()`` fills the remaining 74 bits with
``gen_random_bytes``, so events written inside one transaction (which is every pair of
events about the same aggregate) share a timestamp prefix and sort at random. Handlers were
being called out of order; ``test_events_drain_in_order`` failed intermittently with
``['2', '1', '3']``.

``IDENTITY ALWAYS`` backfills existing rows in physical order on ALTER, which for this table
is insertion order. Those rows are already published, so their relative order no longer
matters — but it is the sane value to land on rather than NULL.

Revision ID: ff37df671223
Revises: cc9339aa209e
Create Date: 2026-08-23 15:15:49.166024
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'ff37df671223'
down_revision: str | None = 'cc9339aa209e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_event', sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False))
    op.create_index('ix_domain_event_seq', 'domain_event', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domain_event_seq', table_name='domain_event')
    op.drop_column('domain_event', 'seq')
    # ### end Alembic commands ###
