import type { Locale } from "@/lib/locale";

export const UI_COPY = {
  "Language": "भाषा",
  "Could not change language. Please try again.": "भाषा नहीं बदल सकी। कृपया फिर प्रयास करें।",
  "AgriVardhak": "कृषिवर्धक",
  "FPO Console": "एफ़पीओ कंसोल",
  "AgriVardhak recommends.": "कृषिवर्धक सुझाव देता है।",
  "A human approves before anything executes.": "हर कार्रवाई से पहले किसी व्यक्ति की स्वीकृति आवश्यक है।",
  "Search farmers, decisions, lots…": "किसान, निर्णय, लॉट खोजें…",
  "Member": "सदस्य",
  "Market prices, weather and hazard climatology are cited in": "मंडी भाव, मौसम और प्राकृतिक जोखिम के स्रोत यहाँ दर्ज हैं:",
  "Sign-in failed.": "साइन इन नहीं हो सका। कृपया विवरण जाँचें।",
  "Enter your username and password.": "अपना उपयोगकर्ता नाम और पासवर्ड दर्ज करें।",
  "Incorrect username or password.": "उपयोगकर्ता नाम या पासवर्ड गलत है।",
  "API unreachable": "सर्वर से संपर्क नहीं हो सका",
  "Could not reach the API. Run `make api`.": "जानकारी नहीं मिल सकी। कृपया बाद में फिर प्रयास करें।",
  "Could not reach the API. Run `make api`, and set AGRI_DEV_TOKEN for an authenticated view.": "जानकारी नहीं मिल सकी। कृपया बाद में फिर प्रयास करें।",
  "Not your view": "यह पृष्ठ आपके खाते के लिए नहीं है",
  "Not visible to you": "यह जानकारी आपके लिए उपलब्ध नहीं है",
  "Organization-internal": "केवल संगठन के लिए",
  "Organization-internal.": "यह जानकारी केवल संगठन के कर्मचारियों के लिए है।",
  "Could not load": "जानकारी लोड नहीं हो सकी",
  "Could not load this decision. Run `make api`.": "यह निर्णय लोड नहीं हो सका। कृपया फिर प्रयास करें।",
  "The decision history is organization-internal.": "निर्णय का इतिहास केवल संगठन के कर्मचारियों के लिए है।",
  "The member list is organization-internal. A farmer sees only their own record.": "सदस्य सूची केवल संगठन के लिए है। किसान केवल अपना विवरण देख सकते हैं।",
  "Buyer negotiations are organization-internal (INV-5).": "खरीदारों से बातचीत केवल संगठन के लिए है (INV-5)।",
  "The risk register is organization-internal.": "जोखिम रजिस्टर केवल संगठन के कर्मचारियों के लिए है।",
  "Data conflicts are organization-internal. A farmer sees their own record, not the reconciliation queue.": "डेटा संबंधी मतभेद केवल संगठन के लिए हैं। किसान अपना विवरण देख सकते हैं, मिलान की कार्यसूची नहीं।",
  "You may not view this farmer. Farmers see only their own record; organization staff see their members.": "आप इस किसान का विवरण नहीं देख सकते। किसान अपना और संगठन के कर्मचारी अपने सदस्यों का विवरण देख सकते हैं।",
  "This view is for organization staff. A farmer account sees their own farm instead — the boundary is enforced by the API, not by hiding this page.": "यह पृष्ठ संगठन के कर्मचारियों के लिए है। किसान खाते में केवल अपने खेत की जानकारी मिलती है। यह सीमा सर्वर पर लागू है।",
  "This view is for a farmer account. Organization staff have the FPO console — the two see different data by design (INV-5).": "यह पृष्ठ किसान खाते के लिए है। संगठन के कर्मचारी एफ़पीओ कंसोल का उपयोग करें — दोनों में अलग जानकारी दिखाई जाती है (INV-5)।",
  "What the collective": "आज समिति की",
  "looks like today": "स्थिति कैसी है",
  "Members, land, crops and open decisions for {organization} — one layer, read before you act.": "{organization} के सदस्य, भूमि, फ़सलें और लंबित निर्णय — कार्रवाई से पहले एक नज़र में समझें।",
  "{count} awaiting approval": "{count} स्वीकृति की प्रतीक्षा में",
  "Organization at a glance": "संगठन एक नज़र में",
  "Briefing": "दैनिक सार",
  "That is a real answer, not an empty state — the briefing stays short so that the day it is long, you read it.": "यह भी एक वास्तविक उत्तर है — सार संक्षिप्त रहता है, ताकि ज़रूरत पड़ने पर महत्वपूर्ण बातें आपका ध्यान खींचें।",
  "Figures are drawn from a real district profile. Market prices and weather come from Agmarknet and Open-Meteo and are real. Generated": "आँकड़े वास्तविक ज़िला विवरण से लिए गए हैं। वास्तविक मंडी भाव और मौसम एगमार्कनेट एवं ओपन-मेटियो से मिलते हैं। तैयार किया गया:",
  "Open decisions": "निर्णय खोलें",
  "Nothing asked yet.": "अभी कोई प्रश्न नहीं पूछा गया है।",
  "Ask the first question": "पहला प्रश्न पूछें",
  "{count} recommendations": "{count} सुझाव",
  "← All decisions": "← सभी निर्णय",
  "Decision packet": "निर्णय विवरण",
  "Approval": "स्वीकृति",
  "Every recommendation here has been decided. Nothing executed without a human approving it first.": "हर सुझाव पर निर्णय लिया जा चुका है। किसी व्यक्ति की स्वीकृति के बिना कोई कार्रवाई नहीं हुई।",
  "Nothing here has happened. Each recommendation waits for a human with the right role.": "अभी कोई कार्रवाई नहीं हुई है। हर सुझाव अधिकृत व्यक्ति की स्वीकृति की प्रतीक्षा में है।",
  "{pending} of {total} still waiting on a human with the right role. Nothing executes before that.": "{total} में से {pending} सुझाव अभी अधिकृत व्यक्ति की प्रतीक्षा में हैं। उससे पहले कोई कार्रवाई नहीं होती।",
  "Frozen evidence": "सुरक्षित स्थिर प्रमाण",
  "Content hash": "सामग्री हैश",
  "Captured": "दर्ज करने का समय",
  "Module versions": "मॉड्यूल संस्करण",
  "Replay": "पुनर्निर्माण",
  "Rebuilt from the snapshot alone and identical — this answer is still reproducible.": "केवल सुरक्षित स्नैपशॉट से दोबारा बनाया गया उत्तर समान है — यह उत्तर अब भी पुनः बनाया जा सकता है।",
  "Rebuilt from the snapshot and it differs:": "स्नैपशॉट से दोबारा बनाया गया उत्तर अलग है:",
  "A coefficient changed without a version bump.": "संस्करण बदले बिना कोई गुणांक बदल गया है।",
  "Membership": "सदस्यता",
  "Farmers": "किसान",
  "{count} members{tract}, across three tracts of the district.": "ज़िले के तीन क्षेत्रों में {count} सदस्य{tract}।",
  " in {tract}": " — {tract} में",
  "Filter by tract": "क्षेत्र के अनुसार चुनें",
  "All tracts": "सभी क्षेत्र",
  "Name": "नाम",
  "Village": "गाँव",
  "Block": "विकास खंड",
  "Tract": "क्षेत्र",
  "Area": "क्षेत्रफल",
  "No farmers match": "कोई किसान नहीं मिला",
  "Showing {start}–{end} of {total}": "{total} में से {start}–{end} दिखाए गए",
  "Previous": "पिछला",
  "Next": "अगला",
  "← All farmers": "← सभी किसान",
  "Plots": "खेत",
  "Growing now": "अभी उग रही फ़सलें",
  "Contributed to lots": "लॉट में योगदान",
  "Past seasons": "पिछले मौसम",
  "Grade": "श्रेणी",
  "health": "फ़सल की स्थिति",
  "no health reading — a field visit would raise this forecast's confidence": "फ़सल की स्थिति दर्ज नहीं है — खेत की जाँच से इस अनुमान की विश्वसनीयता बढ़ेगी",
  "{count} contributing farmers": "{count} योगदान देने वाले किसान",
  "Ready {date}": "{date} को तैयार",
  "No offers on record for this crop. That is a gap, not a market signal.": "इस फ़सल के लिए कोई प्रस्ताव दर्ज नहीं है। यह जानकारी की कमी है, बाज़ार का संकेत नहीं।",
  "No lots on record.": "अभी कोई लॉट दर्ज नहीं है।",
  "Buyer": "खरीदार",
  "Offer": "प्रस्ताव",
  "Distance": "दूरी",
  "Pays in": "भुगतान अवधि",
  "Rejects": "अस्वीकृति दर",
  "no history": "इतिहास उपलब्ध नहीं",
  "The headline price is not what the collective banks. Ask the assistant to score these — distance, payment delay and rejection history all come off first, and rejection history is usually the largest of the three.": "दिखाई गई कीमत समिति की अंतिम आय नहीं है। सहायक से तुलना कराएँ — दूरी, भुगतान में देरी और अस्वीकृति के प्रभाव पहले घटते हैं। अस्वीकृति का असर सामान्यतः सबसे अधिक होता है।",
  "Nothing on the register yet. It fills in when the assistant is asked a question that runs the risk module.": "जोखिम रजिस्टर में अभी कुछ दर्ज नहीं है। सहायक से जोखिम संबंधी प्रश्न पूछने पर यह जानकारी भरती है।",
  "{band} likelihood": "{band} संभावना",
  "{band} impact": "{band} प्रभाव",
  "farmers": "किसान",
  "acres": "एकड़",
  "at stake": "दाँव पर",
  "of years in the record": "अभिलेख के वर्षों में",
  "What would reduce it": "जोखिम कम करने के उपाय",
  "Owned by the {role}": "उत्तरदायी: {role}",
  "review by {date}": "{date} तक समीक्षा",
  "{count} sources": "{count} स्रोत",
  "Data conflicts": "डेटा में मतभेद",
  "best supported": "सबसे अधिक प्रमाणित",
  "{count} sources disagree": "{count} स्रोत असहमत हैं",
  "spread · tolerance {value}%": "अंतर · सहनसीमा {value}%",
  "{count} points outside tolerance.": "सहनसीमा से {count} अंक अधिक।",
  "Inside tolerance, held open for review.": "सहनसीमा के भीतर, समीक्षा के लिए खुला है।",
  "No value has been chosen. Every figure derived from this subject carries": "कोई मान चुना नहीं गया है। इस विषय से निकले हर आँकड़े के साथ",
  "a reduced confidence of {value}%": "{value}% का कम विश्वास स्तर है",
  "reduced confidence": "कम विश्वास स्तर है",
  "until someone with the record in front of them decides.": "जब तक अभिलेख देखकर कोई व्यक्ति निर्णय न ले।",
  "{count} open conflicts": "{count} खुले मतभेद",
  "No open conflicts. Every consequential value currently has one supported answer — which is a real state, not an empty screen.": "कोई खुला मतभेद नहीं है। हर महत्वपूर्ण मान का अभी एक प्रमाणित उत्तर है — यह वास्तविक स्थिति है, खाली स्क्रीन नहीं।",
  "Nothing recorded": "अभी कुछ दर्ज नहीं",
  "No impact to report yet": "अभी कोई प्रभाव दर्ज नहीं है",
  "Impact is measured from recommendations that were approved, executed, and whose outcomes were recorded against a baseline.": "प्रभाव उन सुझावों से मापा जाता है जो स्वीकृत और लागू किए गए तथा जिनके परिणाम प्रारंभिक स्थिति की तुलना में दर्ज किए गए।",
  "An empty panel is the correct answer here. Filling it with activity counts — how many questions were asked, how many packets generated — would be reporting our own busyness as the collective's benefit.": "यहाँ खाली पैनल ही सही उत्तर है। पूछे गए प्रश्नों या तैयार विवरणों की संख्या को समिति का लाभ बताना सही नहीं होगा।",
  "Actions executed": "लागू कार्रवाइयाँ",
  "Attributed": "प्रभाव निर्धारित",
  "Could not attribute": "प्रभाव निर्धारित नहीं हो सका",
  "not followed, or followed too loosely to score": "पालन नहीं हुआ, या मापने योग्य पालन नहीं हुआ",
  "Forecast error": "पूर्वानुमान त्रुटि",
  "{count} scored": "{count} का मूल्यांकन हुआ",
  "Confidence in the claim": "दावे में विश्वास",
  "Attribution strength": "प्रभाव निर्धारण की मज़बूती",
  "{count} attributed": "{count} का प्रभाव निर्धारित",
  "Followed faithfully, moved materially, no confounder we track": "पूरा पालन, उल्लेखनीय बदलाव और कोई ज्ञात अन्य कारण नहीं",
  "Followed and moved, but less decisively": "पालन और बदलाव हुआ, पर कम स्पष्ट रूप से",
  "Moved inside ordinary variation, or had no baseline": "बदलाव सामान्य सीमा में था, या प्रारंभिक स्थिति उपलब्ध नहीं थी",
  "Something else would explain it equally well": "कोई अन्य कारण भी इसे समान रूप से समझा सकता है",
  "Adherence": "पालन",
  "Whether the recommendation was actually followed. Advice nobody took tells us nothing about the advice.": "क्या सुझाव का वास्तव में पालन हुआ। जिस सलाह का पालन नहीं हुआ, उससे उसकी उपयोगिता नहीं आँकी जा सकती।",
  "Search published text": "प्रकाशित पाठ खोजें",
  "crop insurance · soil sample": "फ़सल बीमा · मृदा नमूना",
  "Search": "खोजें",
  "try": "खोजकर देखें",
  "{count} passages": "{count} अंश",
  "context only": "केवल संदर्भ",
  "relevance": "प्रासंगिकता",
  "trust": "विश्वसनीयता",
  "capped at {value}": "अधिकतम सीमा {value}",
  "The licence on this source is unconfirmed, so its confidence is capped below the level a recommendation needs. You may read it; the system may not act on it until a named person clears the licence (ADR-0014).": "इस स्रोत के लाइसेंस की पुष्टि नहीं हुई है। इसलिए इसका विश्वास स्तर सुझाव के लिए आवश्यक स्तर से नीचे सीमित है। इसे पढ़ा जा सकता है, पर अधिकृत व्यक्ति की पुष्टि से पहले इस पर कार्रवाई नहीं हो सकती (ADR-0014)।",
  "Not signed in": "साइन इन नहीं किया गया",
  "This search needs a signed-in session.": "इस खोज के लिए साइन इन करना आवश्यक है।",
  "Nothing searched yet. This index holds the government orders and departmental guidance the system has cached — the same text the risk register cites when it reports policy activity. An English query will find Hindi text: the passages are embedded with a multilingual model, so meaning carries across the two.": "अभी कोई खोज नहीं की गई है। इस सूची में सुरक्षित शासनादेश और विभागीय निर्देश हैं, जिन्हें जोखिम रजिस्टर भी उद्धृत करता है। बहुभाषी खोज हिंदी या अंग्रेज़ी में पूछे गए प्रश्न का अर्थ समझ सकती है।",
  "Nothing matched “{query}”. The corpus is deliberately small — a few hundred passages of real published text, not a web index — so a miss usually means the government has not written about it, rather than that the search failed.": "“{query}” से कोई अंश नहीं मिला। यह कुछ सौ वास्तविक प्रकाशित अंशों का संग्रह है, पूरे वेब की सूची नहीं। परिणाम न मिलने का अर्थ अक्सर संबंधित प्रकाशन उपलब्ध न होना है।",
  "Licence unconfirmed": "लाइसेंस अपुष्ट",
  "Readable, but not actionable": "पढ़ने योग्य, कार्रवाई का आधार नहीं",
  "These passages come from a source whose licence nobody has confirmed. That is not a judgement about the content — it is often the most direct answer to the question — but a fetch cannot assert we are entitled to rely on it, so the system caps it below the confidence a recommendation requires.": "इन अंशों के स्रोत के लाइसेंस की पुष्टि नहीं हुई है। यह सामग्री की गुणवत्ता पर निर्णय नहीं है। उपयोग की अनुमति सुनिश्चित न होने के कारण इनका विश्वास स्तर सुझाव की आवश्यक सीमा से नीचे रखा गया है।",
  "Every passage above is stored verbatim as published, in Hindi, and traces back to a raw cached payload with its own SHA-256 — so a claim built on one can be audited years later against exactly the text it cited (INV-2, ADR-0015).": "हर अंश मूल प्रकाशित हिंदी में सुरक्षित है और अपने एसएचए-256 हैश वाले स्रोत से जुड़ा है। वर्षों बाद भी किसी दावे को उसी उद्धृत पाठ से जाँचा जा सकता है (INV-2, ADR-0015)।",
  "No English version is on record. Select Hindi in the language switch to read the original notice.": "इस सूचना का हिंदी संस्करण उपलब्ध नहीं है।",
  "A translation of this record is not available in the selected language.": "इस अभिलेख का अनुवाद चुनी हुई भाषा में उपलब्ध नहीं है।",
  "Confidence {value}% ({band})": "विश्वास {value}% ({band})",
  "This value is older than its freshness window": "यह मान तय ताज़गी अवधि से पुराना है",
  "stale": "पुराना",
  "Sources disagree about this value — no value has been chosen": "इस मान पर स्रोत असहमत हैं — कोई मान नहीं चुना गया है",
  "conflict": "मतभेद",
  "Approve": "स्वीकृत करें",
  "Approve with a different amount": "अलग राशि के साथ स्वीकृत करें",
  "Reject": "अस्वीकृत करें",
  "A rejection needs a reason. It is the clearest signal the system gets about what it got wrong.": "अस्वीकृति का कारण आवश्यक है। इससे प्रणाली को अपनी गलती समझने में सहायता मिलती है।",
  "Approved amount (₹)": "स्वीकृत राशि (₹)",
  "Recorded as a modification, not a plain approval — so the system learns its figure was not the one you agreed.": "इसे सामान्य स्वीकृति नहीं, संशोधन के रूप में दर्ज किया जाएगा — ताकि प्रणाली समझे कि आप उसकी प्रस्तावित राशि से सहमत नहीं थे।",
  "Why not? (required)": "अस्वीकृति का कारण (आवश्यक)",
  "Note (optional)": "टिप्पणी (वैकल्पिक)",
  "Confirm rejection": "अस्वीकृति की पुष्टि करें",
  "Confirm approval": "स्वीकृति की पुष्टि करें",
  "Cancel": "रद्द करें",
  "Mark as executed": "लागू किया गया चिह्नित करें",
  "Records what was actually done, so the outcome can be attributed later (INV-7).": "वास्तव में हुई कार्रवाई दर्ज करता है, ताकि बाद में उसके परिणाम का प्रभाव निर्धारित किया जा सके (INV-7)।",
  "Awaiting {role}. Nothing has happened yet.": "{role} की प्रतीक्षा है। अभी कोई कार्रवाई नहीं हुई है।",
  "by the {role} on {date}": "{date} को {role} द्वारा",
  "modified to": "संशोधित राशि",
  "Request failed. Please try again.": "अनुरोध पूरा नहीं हुआ। कृपया फिर प्रयास करें।",
  "Page not found": "पृष्ठ नहीं मिला",
  "The page you requested could not be found.": "आपके अनुरोधित पृष्ठ का पता नहीं मिला।",
  "Return home": "मुख्य पृष्ठ पर जाएँ",
} as const;

export type CopyKey = keyof typeof UI_COPY;
export type CopyValues = Record<string, string | number>;
export type Copy = (key: CopyKey, values?: CopyValues) => string;

export function interfaceCopy(locale: Locale): Copy {
  return (key, values = {}) => {
    const template = locale === "hi" ? UI_COPY[key] : key;
    return template.replace(/\{(\w+)\}/g, (match, name: string) => String(values[name] ?? match));
  };
}
